### ISSUE TITLE
【302、303】代码错误

### ISSUE THREAD

**Issue by ReganHe** [HcySunYang/code-for-vue-3-book#105]
1. 302页第一个代码块第9行 
`const subTree = render.call(ctx,ctx)`应改为 `const subTree = render.call(state,state)`
2. 303页第二个代码块第8行 
`const subTree = render.call(ctx,ctx)`应改为 `const subTree = render.call(state,state)`

**Comment by HcySunYang** [comment]
https://github.com/HcySunYang/code-for-vue-3-book/issues/34
