### ISSUE TITLE
【第310页】set 使用有误 应当返回一个布尔值

### ISSUE THREAD

**Issue by yucccc** [HcySunYang/code-for-vue-3-book#155]
代码 27-34 行中 对属性进行set 应当返回一个布尔值

**Comment by HcySunYang** [comment]
![e86f1942aa2b4dd281168a7cb6f19ec](https://user-images.githubusercontent.com/14146560/200720301-9a875a3e-3194-455b-a7b4-36ae981f8880.jpg)

如图，在这个花括号的下面添加一句代码：`return true`，缩进与花括号对其

**Comment by HcySunYang** [comment]
![6c0c13713d3a8b0825ffc383543ffd9](https://user-images.githubusercontent.com/14146560/200720489-7539d574-f7d0-4ca6-b349-1c0ce7d62716.jpg)

313 页也需要添加，如上图
