### ISSUE TITLE
6印 252页  “小于” 应该是 “大于”

### ISSUE THREAD

**Issue by EasyForever** [HcySunYang/code-for-vue-3-book#157]
图10-10下方一段文本中的：索引newStartIdx和索引oldStartIdx的值都 “小于” newEndIdx和oldEndIdx，其中 “小于” 应该是 “大于” 才正确。

**Comment by hexiaokang** [comment]
是的，我也发现了！

**Comment by HcySunYang** [comment]
![1dd4fad59f553e4c63ebc5780ccb72e](https://user-images.githubusercontent.com/14146560/200719803-61427bfb-d5af-4958-8cd1-9dd516e08821.jpg)

小于改为大于

**Comment by EasyForever** [comment]
@HcySunYang 书看完好久了，忘记回来关问题了。(。・＿・。)ﾉI’m sorry~
