### ISSUE TITLE
【第384页】 多余的console.log

### ISSUE THREAD

**Issue by yucccc** [HcySunYang/code-for-vue-3-book#159]
dump 已经会默认输出且 dump(ast)并没有返回 
因此不需要再 console.log( dump(ast) )
直接调用dump(ast)同效

**Comment by HcySunYang** [comment]
![e8820164cc928cc8415f17c955b772e](https://user-images.githubusercontent.com/14146560/200719458-0e1e719d-3ae2-4bf0-9e8a-d07df65ecbb1.jpg)

将上图中的：`console.log(dump(ast))` 改为 `dump(ast)`
