### ISSUE TITLE
【252页】图10-10 新旧两组子节点以及真实DOM节点的状态 。 newEndIdx和newStartIdx标注错误

### ISSUE THREAD

**Issue by CaoXueLiang** [HcySunYang/code-for-vue-3-book#170]
新字节点中：newEndIdx 对应的应该是 `p-2`， newStartIdx 对应的应该是 `p-1`

[![20220912114424.jpg](https://i.postimg.cc/MK8LV6c2/20220912114424.jpg)](https://postimg.cc/F1DGQQgD)

**Comment by HcySunYang** [comment]
重复 [252https://github.com/HcySunYang/code-for-vue-3-book/issues/122](https://github.com/HcySunYang/code-for-vue-3-book/issues/122)
