### ISSUE TITLE
【58页】嵌套的 effect 与 effect 栈 的处理逻辑有遗漏

### ISSUE THREAD

**Issue by w457130328** [HcySunYang/code-for-vue-3-book#33]
![image](https://user-images.githubusercontent.com/40887913/155842492-5d307b7e-4c4c-4274-867f-ae485343fa76.png)

**Comment by fyzhu** [comment]
确实有这个问题

**Comment by HcySunYang** [comment]
4.7 节调度执行会处理这个问题哦~

**Comment by fyzhu** [comment]
> 4.7 节调度执行会处理这个问题哦~

4.7 解决的不是这个问题，4.7 解决的是过渡状态的问题，这个不是过渡状态，这个是bug，是由于deps 里添加了重复的 activeEffect 导致的
