### ISSUE TITLE
【60页】避免无限递归循环 的处理逻辑有遗漏

### ISSUE THREAD

**Issue by w457130328** [HcySunYang/code-for-vue-3-book#41]
书中代码解决了单个副作用函数 obj.foo++ 造成的死循环问题。
```javascript
effect(() => obj.foo++)
```
但是没有解决或提及多个副作用函数造成的死循环问题。
```javascript
effect(() => obj.foo++);
effect(() => obj.foo++);
```
运行示例图

![image](https://user-images.githubusercontent.com/40887913/155864273-3fc0fd19-c89b-4abd-bb18-015e3d60b1ed.png)

**Comment by HcySunYang** [comment]
这个问题在 131 也有讲哦~
