### ISSUE TITLE
56页组件嵌套使用 effect 函数表示，应该将 Foo.render() 给去掉

### ISSUE THREAD

**Issue by shibin-cli** [HcySunYang/code-for-vue-3-book#50]
56页组件嵌套使用effect 函数，应该将 Foo.render给去掉
![image](https://user-images.githubusercontent.com/72774429/156088519-ab58d614-80ef-4e01-9c0c-92e1e4942280.png)

```diff
effect(() => {
-    Foo.render()
    // 嵌套
    effect(() => {
        Bar.render()
    })
})
```

**Comment by HcySunYang** [comment]
这个是有意的哦
