### ISSUE TITLE
【47页】这段代码，有可能会导致读取不到`obj`里属性的值。

### ISSUE THREAD

**Issue by sunnyxujian** [HcySunYang/code-for-vue-3-book#67]
这段代码如果不存在`activeEffect`，会导致读取不到`obj`里属性的值。
建议改成：
```js
// ...
get(target, key, receiver) {
  if(activeEffect) {
   // 收集effect和key的关系...
  }
  return target[key]
},
// ...
```
![image](https://user-images.githubusercontent.com/24877853/157841471-643a48ae-a60e-46ad-848d-5ab483c1f813.png)

**Comment by HcySunYang** [comment]
https://github.com/HcySunYang/code-for-vue-3-book/issues/6
重复问题
