### ISSUE TITLE
4.4切换与cleanup [疑问]

### ISSUE THREAD

**Issue by HaoYuToDo** [HcySunYang/code-for-vue-3-book#83]
![1647585802991](https://user-images.githubusercontent.com/18275148/158950667-9f9d210d-fade-4665-97b2-f5cd6c021c54.jpg)

调用循环cleanup之前每次都会执行effectFn.deps=[],那这个for循环一值都是空数组，有什么意义？

**Comment by yangliguo7** [comment]
hi ~ ; 我在阅读的时候·也有这个疑问? 我并不了解为什么cleanup需要这个做去清除副作用依赖？

**Comment by wm1234566** [comment]
执行流程：
(1)effect(...)执行  
(2)effectFn.deps为空数组， 
(3)effectFn() 执行
(4)cleanup()执行，(2)为空数组没意义
(5)activeEffect 为effectFn
(6) fn()执行，obj.ok被读取，触发track函数 obj.ok的桶存储了activeEffect也就是effectFn，activeEffect.deps.push(deps)
(7)effectFn.deps push了整个set，即obj.ok的所有副作用函数，
(8) obj.text被读取，触发track函数 obj.text的桶存储了activeEffect也就是effectFn，activeEffect.deps.push(deps)
(9)
setTimeout(() => {
  obj.ok = false
  setTimeout(() => {
    obj.text = 'hello vue3'
  }, 1000)
}, 1000)
(10) obj.ok 被设触发trigger 他执行的他收集的作用函数，也就是(6)中的deps，里面的时effectFn，也就是
() => {
    cleanup(effectFn)
   // debugger
    // 当调用 effect 注册副作用函数时，将副作用函数复制给 activeEffect
    activeEffect = effectFn
    fn()
  }
(11)再次触发 cleanup(effectFn) effectFn.deps  中这个时候有两个set 分别时obj.ok 和obj.text的副作用函数集合，
for (let i = 0; i < effectFn.deps.length; i++) {
    const deps = effectFn.deps[i];
    deps.delete(effectFn)
  }
  effectFn.deps.length = 0
然后分别读取两个集合，删除相同的effectFn函数，这个时候其实是删除了，桶中obj.ok和obj.text中set中的effctFn
因为这是引用
所以，cleanup执行玩之后，obj.ok和obj.text中set中没有（effctFn）依赖函数l
(12) fn执行，obj.ok被读取，触发track，被存入obj.ok的set中，然后obj.ok为false，obj.text不会执行，他不会将副作用存入他的
set
(13)修改obj.text 触发trigger，找不到effectFn副作用函数执行，
这样就实现了优化，
