### ISSUE TITLE
【196页】疑问

### ISSUE THREAD

**Issue by yang-Ann** [HcySunYang/code-for-vue-3-book#88]
代码实例2的13行 patchElement 函数书上是不是漏了, 我看代码仓库里有 ( 渲染器-8.6 )

**Comment by HcySunYang** [comment]
在后面讲到 patchElement 的时候才会把代码贴出来，往后看哦~

**Comment by idonteatcookie** [comment]
> 的时候才会把代码贴出来，往后看哦~

代码在8.9才贴出来，但是在8.8的示例中需要该函数才能运行。
