### ISSUE TITLE
【110页】浅响应也应该 track

### ISSUE THREAD

**Issue by candy-Tong** [HcySunYang/code-for-vue-3-book#91]
![image](https://user-images.githubusercontent.com/20377280/159261476-d70f5651-a098-4646-8e38-34449f155c89.png)
![image](https://user-images.githubusercontent.com/20377280/159261447-5bb70cd6-5c35-46d6-8570-00f68e097a61.png)

浅响应也应该 track，16行代码 track 应该在 return 前，否则 shallowReactive 就没有任何响应性了， 永远页不会 track 了

**Comment by hotYan** [comment]
#13

**Comment by HcySunYang** [comment]
https://github.com/HcySunYang/code-for-vue-3-book/issues/13

重复问题
