### ISSUE TITLE
【62页】案例错误

### ISSUE THREAD

**Issue by clyan** [HcySunYang/code-for-vue-3-book#92]
如下图描述：我想该案例中应该将标记的那段语句删除

![微信图片_20220323150102](https://user-images.githubusercontent.com/46644748/159642182-e2d20cfc-3fc1-42e1-a432-2bb6730a294d.jpg)

**Comment by HcySunYang** [comment]
https://github.com/HcySunYang/code-for-vue-3-book/issues/58
重复问题
